name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
         contents: write
         actions: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "Raphael Ehindero"
          git config --global user.email "raph941@gmail.com"

      - name: Add upstream remote
        run: |
          git remote add upstream ${{ github.event.repository.parent.html_url || 'https://github.com/sourcegraph/about.git' }}
          git fetch upstream

      - name: Sync fork with upstream (fast-forward only)
        run: |
          # Reset main to match upstream exactly - no merge commits
          git checkout main
          git reset --hard upstream/main
          git push --force origin main
